### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by sidahuja1** [DSCI-310-2024/DSCI-310-Group-18_wine-quality-predictor#1]
From Milestone 1 page: 
In the main README.md file for this project you should include: - the project title - the list of contributors/authors - a short summary of the project (view from 10,000 feet) - how to run your data analysis - a list of the dependencies needed to run your analysis - the names of the licenses contained in LICENSE.md

**Comment by adaws01** [comment]
I've outlined the above sections, and completed the authors and licenses sections. 

We'll need to update the README based on what research question we settle on.
