### ISSUE TITLE
Methods/Results: EDA and Feature Selection

### ISSUE THREAD

**Issue by sidahuja1** [DSCI-310-2024/DSCI-310-Group-18_wine-quality-predictor#10]
See [Milestone 1](https://ubc-dsci.github.io/dsci-310-student/milestone1.html) for guidelines
See [breast cancer predictor](https://github.com/ttimbers/breast_cancer_predictor_py/blob/v0.0.4/src/breast_cancer_predictor_report.ipynb) for example

**Comment by sidahuja1** [comment]
Breast cancer predictor example has a good method for feature selection. See the predictor distributions. Pick features where the distributions between classes are somewhat distinct

**Comment by adaws01** [comment]
Thoughts for EDA: 

Some variables might be strongly correlated to quality alone, while others may show little direct correlation, but exhibit strong trends combined with other variables.. For example, considering residual sugar and pH, we may find that a sweet wine benefits from a higher pH than a dry wine typically would. What patterns exist concerning multiple variables? We could consider using correlation matrices to examine patterns involving multiple variables including:

-  Residual Sugar and Chlorides (balance of sweet and savoury) on Quality
- Sulphates and Sulphur Dioxide (which I believe are preservatives) on Quality
