### ISSUE TITLE
Create/Update CONTRIBUTING file

### ISSUE THREAD

**Issue by sidahuja1** [DSCI-310-2024/DSCI-310-Group-18_wine-quality-predictor#2]
From Milestone 1: 
It is a good practice to include information about how others, outside the core team, can contribute to your project somewhere in your repository. This is typically done as a separate file in the repository called CONTRIBUTING.md. Here are some examples of this file:

[Altair](https://github.com/altair-viz/altair/blob/master/CONTRIBUTING.md)
[dplyr](https://github.com/tidyverse/dplyr/blob/master/.github/CONTRIBUTING.md)
[Atom editor](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) (very comprehensive)

Note 1 - this document should live in the root of your public GitHub.com repository.
Note 2 - If you all, or even part, of someone else’s code of conduct, be sure to make this clear by attributing them.

**Comment by adaws01** [comment]
Updated Contributing.md to reflect this project as part of a class. Are we happy with what we have? Or is there more to add?
