### ISSUE TITLE
Add References 

### ISSUE THREAD

**Issue by sidahuja1** [DSCI-310-2024/DSCI-310-Group-18_wine-quality-predictor#7]
See [Milestone 1](https://ubc-dsci.github.io/dsci-310-student/milestone1.html) for guidelines
See [breast cancer predictor](https://github.com/ttimbers/breast_cancer_predictor_py/blob/v0.0.4/src/breast_cancer_predictor_report.ipynb) for example

**Comment by adaws01** [comment]
Cited our data set, and some information regarding the type of wine we're looking into (from verified sources in Portugal).
