### ISSUE TITLE
Update environment file

### ISSUE THREAD

**Issue by sidahuja1** [DSCI-310-2024/DSCI-310-Group-18_wine-quality-predictor#8]
We are planning to use R for the analysis --> should we create a yaml or renv file? I think all the packages we'll end up using are available through conda. What do you guys think?

From Milestone 1:
Include the necessary files (e.g., environment.yml) so others can reproduce your work on their machine.
Note - this document should live in the root of your public GitHub.com repository.

For this project, we will eventually be making the computation environment reproducible through containerization with Docker. For milestone 1 however, we will start with using a virtual environment as our first step towards this. You can use either conda or renv for this. Be sure to include the necessary files (e.g., environment.yml) so others can reproduce your work. Be sure to include documentation of how to use the environment with your project as well in the README.md file. Finally, make sure the versions of all software and software packages used in the analysis are recorded in the file that specifies the environment.

**Comment by adaws01** [comment]
I think I'd argue we use a yml file with Conda as our main package manager. It's versatile, and like you've already said, I think it'll have everything we need. In the event we can't use Conda for some aspect of our project (I doubt we'll face this), we could always figure out extending its' functionality. I'll do my best to set up an environment.yml, and I'll push this through a new branch that you guys can review.
